# docker-compose.yml
version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "4000:5000"
    volumes:
      - ./backend:/server
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
