# docker-compose.yml
version: "3.9"

services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    restart: unless-stopped
    environment:
      NODE_ENV: production

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:4000
    depends_on:
      - backend
    restart: unless-stopped
